### ISSUE TITLE
The Plugin does not work

### ISSUE THREAD

**Issue by DarkXero-dev** [Guts/mkdocs-rss-plugin#322]
Hello.. 

I am on ArchLinux installed mkdocs via `pacman` and the plugin from the **AUR** I am using the material theme... Added `-rss` to `mkdocs.yml` when I test it errors out with
```Bash
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/__main__.py", line 268, in serve_command
    serve.serve(**kwargs)
  File "/usr/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = get_config()
             ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/commands/serve.py", line 43, in get_config
    config = load_config(
             ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/config/base.py", line 374, in load_config
    errors, warnings = cfg.validate()
                       ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/config/base.py", line 231, in validate
    run_failed, run_warnings = self._validate()
                               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/config/config_options.py", line 186, in validate
    return self.run_validation(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/config/config_options.py", line 1075, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/usr/lib/python3.12/site-packages/mkdocs/config/config_options.py", line 1113, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkdocs/config/config_options.py", line 1131, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/mkdocs_rss_plugin/plugin.py", line 37, in <module>
    from mkdocs_rss_plugin.util import Util
  File "/usr/lib/python3.12/site-packages/mkdocs_rss_plugin/util.py", line 22, in <module>
    from cachecontrol import CacheControl
ModuleNotFoundError: No module named 'cachecontrol'
```
No idea why it's failing. Am I missing something ?

**Comment by Guts** [comment]
Hello,

Your issue title is quite interesting since the plugin is quite heavily used among thousands or mkdocs websites. Maybe you should rename it with something more specific like "I can't make the plugin work on ArchLinux".

In the meanwhile, can you give more details on your environment:

- Python version: 3.12
- mkdocs version
- material...

I don't know about AUR but cachecontrol is one the required dependencies and should have been installed with the plugin from pypi.org:

https://github.com/Guts/mkdocs-rss-plugin/blob/a1685169f127cf6f59dc8dc086629b64534a82d4/requirements/base.txt#L4

**Comment by DarkXero-dev** [comment]
@Guts 

- Python version: 3.12
- MKDocs v1.6.0 >> [**Here**](https://archlinux.org/packages/extra/any/mkdocs/)
- MKDocs-Material: 9.5.33-1 >> [**Here**](https://aur.archlinux.org/packages?O=0&K=mkdocs-material)

I see cachecontrol [**here**](https://archlinux.org/packages/extra/any/python-cachecontrol/) I will install n try again

**Comment by Guts** [comment]
> Am not the only one a friend who made a video about MKDocs is having same issue.

Is your friend also on Arch?

**Comment by Guts** [comment]
The error message indicates that cacheControl is not installed or not found: 

> ModuleNotFoundError: No module named 'cachecontrol'

It's not related to the plugin but to the Python environment.

Can you try to clone the repository locally and install from it directly? Something like this from your Python (virtual) environment, adapting the path to your local copy:

```sh
python -m pip install ~/Git/mkdocs-rss-plugin
```

**Comment by DarkXero-dev** [comment]
@Guts 

No my friend is on Debian and he did it via python not the AUR lol. On Arch `pip install` doesn't work.

Anyway seems to have worked by cloning repo then cd into it n running `sudo python setup.py install` now it's not complaining anymore. 

Last question, how do I add a menu entry for RSS feed so I can add to RSS reader ?

**Comment by Guts** [comment]
It's still weird 🤔.  
Thanks for feedback and following up.

**Comment by DarkXero-dev** [comment]
@Guts 

Thanks. However it works is good. Will check with AUR package maintainer.
