### ISSUE TITLE
'NoneType' object is not iterable when using 0.19.0

### ISSUE THREAD

**Issue by prcr** [Guts/mkdocs-rss-plugin#95]
Hello,

When [trying to build](https://github.com/codacy/docs/pull/876) a site that I maintain using mkdocs-rss-plugin 0.19.0 I get the following:

```
Run mkdocs build
  mkdocs build
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.7/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.7/x64/lib
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/runner/work/docs/docs/site 
ERROR   -  Error reading page 'release-notes/cloud/cloud-2021-08.md': 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.7/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/mkdocs/commands/build.py", line 174, in _populate_page
    page.content = config['plugins'].run_event(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/mkdocs_rss_plugin/plugin.py", line 214, in on_page_content
    categories=self.util.get_categories_from_meta(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/mkdocs_rss_plugin/util.py", line 244, in get_categories_from_meta
    for category_label in categories_labels:
TypeError: 'NoneType' object is not iterable
Error: Process completed with exit code 1.
```

It's possible that this issue has to do with the [existing metadata](https://github.com/codacy/docs/blob/master/docs/release-notes/cloud/cloud-2021-08.md) for the page where the process stopped.

**Comment by Guts** [comment]
Thanks for taking time to report it.

Could you chare the relevant configuration section of your mkdocs.yml please?

**Comment by prcr** [comment]
Yes, here it is:

https://github.com/codacy/docs/blob/dependabot/pip/mkdocs-rss-plugin-0.19.0/mkdocs.yml#L96-L100

**Comment by Guts** [comment]
Sorry, my bad: introducing the categories logic, I forgot to handle case where... they are not set in the configuration! It should be fixed and deployed as 0.19.1.

Tell me
